# Generated by Django 3.1.5 on 2021-01-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('temperature', models.CharField(max_length=30, verbose_name='temperature')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'indicator',
                'verbose_name_plural': 'indicators',
            },
        ),
    ]
