# Generated by Django 3.1.5 on 2021-01-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Belarus', (('Minsk Region', 'Minsk Region'), ('Gomel Region', 'Gomel Region'), ('Brest Region', 'Brest Region'), ('Grodno Region', 'Grodno Region'), ('Vitebsk Region', 'Vitebsk Region'), ('Mogilev Region', 'Mogilev Region'))), ('Ukraine', (('Kyiv', 'Kyiv'), ('Chernihiv', 'Chernihiv')))], max_length=300)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['-region'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-city'], 'verbose_name': 'indikator', 'verbose_name_plural': 'indikators'},
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.location', verbose_name='location'),
        ),
    ]
