# Generated by Django 3.1.5 on 2021-01-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210127_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'rainfall',
                'verbose_name_plural': 'rainfalls',
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-city'], 'verbose_name': 'weather', 'verbose_name_plural': 'weathers'},
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('Belarus', (('Minsk Region', 'Minsk Region'), ('Gomel Region', 'Gomel Region'), ('Brest Region', 'Brest Region'), ('Grodno Region', 'Grodno Region'), ('Vitebsk Region', 'Vitebsk Region'), ('Mogilev Region', 'Mogilev Region'))), ('Ukraine', (('Kyiv', 'Kyiv'), ('Chernihiv', 'Chernihiv')))], max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='rainfall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rainfall', verbose_name='rainfall'),
        ),
    ]
