# Generated by Django 3.1.5 on 2021-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210130_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfall',
            name='degree_of_strength',
            field=models.CharField(choices=[('degree_of_strength', (('Light', 'Light'), ('Medium', 'Medium'), ('Strong', 'Snow')))], max_length=30, null=True),
        ),
    ]
