# Generated by Django 3.1.5 on 2021-01-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210130_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Strong', 'Strong')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'strength',
                'verbose_name_plural': 'strengths',
                'ordering': ['-degree'],
            },
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='degree_of_strength',
        ),
        migrations.AddField(
            model_name='rainfall',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.strength', verbose_name='strength'),
        ),
    ]
