# Generated by Django 3.1.5 on 2021-01-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210131_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='strength',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.strength', verbose_name='strength'),
        ),
    ]
