# Generated by Django 3.1.5 on 2021-02-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-id'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
    ]
